project_type: php
test:
  phpunit:
    command:
      - php artisan key:generate
      - php artisan migrate --database=mysql_test
      - php -dzend_extension=xdebug.so vendor/bin/phpunit
        --coverage-clover=.framgia-ci-reports/coverage-clover.xml
        --coverage-html=.framgia-ci-reports/coverage
